name = "MinMax"
uuid = "b1550695-b302-4b9c-b88c-ce86aab55d81"
version = "0.1.0"
authors = ["Caleb Jacobs <calebjacobs210@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
LinearAlgebra = "1.12.0"
Polynomials = "4.1.0"
